import logging
import os
import random
import uuid
from datetime import datetime
from zoneinfo import ZoneInfo

from telegram import (
    InlineQueryResultArticle,
    InputTextMessageContent,
    Update,
)
from telegram.ext import (
    Application,
    CommandHandler,
    ContextTypes,
    InlineQueryHandler,
)

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)

MOSCOW_TZ = ZoneInfo("Europe/Moscow")
PLAYERS = [
    "Messi (Lionel Andrés Messi Cuccittini)",
    "Xavi (Xavier Hernández Creus)",
    "Busquets (Sergio Busquets Burgos)",
    "Iniesta (Andrés Iniesta Luján)",
    "Piqué (Gerard Piqué Bernabeu)",
    "Puyol (Carles Puyol Saforcada)",
    "Migueli (Miguel Bernardo Bianquetti)",
    "Víctor Valdés (Víctor Valdés Arribas)",
    "Jordi Alba (Jordi Alba Ramos)",
    "Rexach (Carles Rexach Cerdà)",
    "Ter Stegen (Marc-André ter Stegen)",
    "Amor (Guillermo Amor Martínez)",
    "Zubizarreta (Andoni Zubizarreta Urreta)",
    "Dani Alves (Daniel Alves da Silva)",
    "Segarra (Joan Segarra Iracheta)",
    "Alexanco (José Ramón Alexanco Ventosa)",
    "Rifé (Joaquim Rifé Climent)",
    "Asensi (Juan Manuel Asensi Ripoll)",
    "Ramallets (Antonio Ramallets Simón)",
    "Guardiola (Josep Guardiola Sala)",
    "Sergi (Sergi Barjuán Esclusa)",
    "Carrasco (Francisco José Carrasco Hidalgo)",
    "Sergi Roberto (Sergi Roberto Carnicer)",
    "Torres (Antonio Torres García)",
    "Tente Sánchez (José Vicente Sánchez Felip)",
    "César (César Rodríguez Álvarez)",
    "Bakero (José María Bakero Escudero)",
    "Mascherano (Javier Alejandro Mascherano)",
    "Sadurní (Salvador Sadurní Urpí)",
    "Gallego (Francisco Fernández Rodríguez)",
    "Eladio (Eladio Silvestre Graells)",
    "Pedro (Pedro Eliezer Rodríguez Ledesma)",
    "Olivella (Ferran Olivella Pons)",
    "Gracia (Sigfrido Gracia Royo)",
    "Víctor Muñoz (Víctor Muñoz Manrique)",
    "Begiristain (Aitor Begiristain Mújika)",
    "Rakitić (Ivan Rakitić)",
    "Basora (Estanislao Basora Brunet)",
    "Ferrer (Albert Ferrer Llopis)",
    "Luis Enrique (Luis Enrique Martínez García)",
    "Julio Alberto (Julio Alberto Moreno Casas)",
    "Nadal (Miquel Àngel Nadal Homar)",
    "De Jong (Frenkie de Jong)",
    "Cocu (Phillip John William Cocu)",
    "Eusebio (Eusebio Sacristán Mena)",
    "Vergés (Martí Vergés Massa)",
    "Luis Suárez (Luis Alberto Suárez Díaz)",
    "Fusté (Josep Maria Fusté Blanch)",
    "Marcial (Marcial Manuel Pina Morales)",
    "Seguer (José Seguer Sans)",
    "Koeman (Ronald Koeman)",
    "Esteban Vigo (Esteban Vigo Benítez)",
    "Olmo (Antonio Olmo Ramírez)",
    "Abelardo (Abelardo Fernández Antuña)",
    "Kluivert (Patrick Stephan Kluivert)",
    "Kubala (László Kubala Stecz)",
    "Stoichkov (Hristo Stoichkov Stoichkov)",
    "Reiziger (Michael John Reiziger)",
    "Figo (Luís Filipe Madeira Caeiro Figo)",
    "Pedri (Pedro González López)",
    "Artola (Pedro María Artola Urrutia)",
    "Gonzalvo III (Mariano Gonzalvo Falcón)",
    "De la Cruz (Jesús Antonio de la Cruz Gallego)",
    "Márquez (Rafael Márquez Álvarez)",
    "Schuster (Bernhard Schuster)",
    "Rivaldo (Vítor Borba Ferreira Gomes)",
    "Costas (Enrique Álvarez Costas)",
    "Laudrup (Michael Laudrup)",
    "Villaverde (Ramón Alberto Villaverde Vázquez)",
    "Gerardo (Gerardo Miranda Concepción)",
    "Julio Salinas (Julio Salinas Fernández)",
    "Zaldúa (José Antonio Zaldúa Urdanavia)",
    "Frank de Boer (Franciscus de Boer)",
    "Araújo (Ronald Federico Araújo da Silva)",
    "Juan Carlos (Juan Carlos Pérez López)",
    "Curta (José Puig Puig)",
    "Ronaldinho (Ronaldo de Assis Moreira)",
    "Ferran Torres (Ferran Torres García)",
    "Pereda (Jesús María Pereda Ruiz de Temiño)",
    "Gensana (Enric Gensana Merola)",
    "Eto'o (Samuel Eto'o Fils)",
    "Velasco (Juan Zambudio Velasco)",
    "Robert (Roberto Fernández Bonillo)",
    "Escolà (Josep Escolà Segalès)",
    "Tejada (Justo Tejada Martínez)",
    "Gabri (Gabriel Francisco Garcia de la Torre)",
    "Zabalza (Pedro María Zabalza Inda)",
    "Abidal (Éric Sylvain Abidal)",
    "Lewandowski (Robert Lewandowski)",
    "Koundé (Jules Olivier Koundé)",
    "Adriano (Adriano Correia Claro)",
    "Keita (Seydou Keita)",
    "Neymar (Neymar da Silva Santos Júnior)",
    "Calvet (Francisco Calvet Puig)",
    "Dembélé (Masour Ousmane Dembélé)",
    "Neeskens (Johannes Jacobus Neeskens)",
    "Urruti (Francisco Javier González Urruticoechea)",
    "Marcos Alonso (Marcos Alonso Peña)",
    "Raphinha (Raphael Dias Belloli)",
    "Cruyff (Hendrik Johannes Cruijff)",
    "Urbano (Urbano Ortega Cuadros)",
    "Benítez (Julio César Benítez Amoedo)",
    "Bosch (Andrés Bosch Pujol)",
    "Luis Suárez (Luis Suárez Miramontes)",
    "Biosca (Gustavo Biosca Pagés)",
    "Oleguer (Oleguer Presas Renom)",
    "Goikoetxea (Jon Andoni Goikoetxea Lasa)",
    "Manchón (Eduardo Manchón Molina)",
    "Raich (José Raich Garriga)",
    "Saviola (Javier Pedro Saviola Fernández)",
    "Moratalla (Josep Moratalla Claramunt)",
    "Eric Garcia (Eric Garcia Martret)",
    "Balde (Alejandro Balde Martínez)",
    "Gavi (Pablo Martín Páez Gavira)",
    "Gonzalvo II (Josep Gonzalvo Falcón)",
    "Zuviría (Rafael Dalmacio Zuviría Rodríguez)",
    "Bojan (Bojan Krkić Pérez)",
    "Eulogio Martínez (Eulogio Martínez Ramiro)",
    "Deco (Anderson Luís de Souza)",
    "Reina (Miguel Reina Santos)",
    "Lenglet (Clément Nicolas Laurent Lenglet)",
    "Zaballa (Pedro Tomás Zaballa Barquín)",
    "Ramos (José Antonio Ramos Huete)",
    "Calderé (Ramón María Calderé del Rey)",
    "Manolo (José Manuel Martínez Toral)",
    "Lamine Yamal (Lamine Yamal Nasraoui Ebana)",
    "Van Bronckhorst (Giovanni Christiaan van Bronckhorst)",
    "Nogués (Juan José Nogués Portalatín)",
    "Evaristo (Evaristo de Macedo Filho)",
    "Fàbregas (Francesc Fàbregas Soler)",
    "Martín (Mariano Martín Alonso)",
    "Motta (Thiago Motta Santon Olivares)",
    "Foncho (Alfonso María Rodríguez Salas)",
    "Hesp (Rudolfus Hubertus Hesp)",
    "Serna (Ricardo Jesús Serna Orozco)",
    "Bravo (José Bravo Domínguez)",
    "Overmars (Marc Overmars)",
    "Alexis Sánchez (Alexis Alejandro Sánchez Sánchez)",
    "Quini (Enrique de Castro González)",
    "Fermín (Fermín López Marín)",
    "Lineker (Gary Winston Lineker)",
    "Gerard (Gerard López Segú)",
    "Umtiti (Samuel Yves Umtiti)",
    "Piera (Vicente Piera Pañella)",
    "Elias (Jaime Elias Casas)",
    "Cubarsí (Pau Cubarsí Paredes)",
    "Simonsen (Allan Rodenkam Simonsen)",
    "Sylvinho (Sylvio Mendes Campos Júnior)",
    "Clares (Manuel Clares García)",
    "Rodri (Francisco Rodríguez García)",
    "Kocsis (Sándor Kocsis Péter)",
    "Garay (Jesús Garay Vecino)",
    "Giuly (Ludovic Vincent Giuly)",
    "Semedo (Nélson Cabral Semedo)",
    "Ansu Fati (Anssumane Fati Vieira)",
    "Henry (Thierry Daniel Henry)",
    "Rosalén (Manuel Rosalén Bellón)",
    "De la Peña (Iván de la Peña López)",
    "Villa (David Villa Sánchez)",
    "Martí Filosia (Narcís Martí Filosia)",
    "Yaya Touré (Gnégnéri Yaya Touré)",
    "Busquets (Carles Busquets Barroso)",
    "Sospedra (Jaime Sospedra Juliá)",
    "Zabalo (Ramón de Zabalo Zubiaurre)",
    "Guðjohnsen (Eiður Smári Guðjohnsen)",
    "Cayetano Ré (Cayetano Ré Ramírez)",
    "Flotats (Isidro Flotats Vilanova)",
    "Pedrol (Esteban Pedrol Albareda)",
    "Soler (Miquel Soler Sarasols)",
    "Heredia (Juan Carlos Heredia Araya)",
    "Roger (Roger García Junyent)",
    "Samitier (Josep Samitier Vilalta)",
    "Giovanni (Giovanni Silva de Oliveira)",
    "Coutinho (Philippe Coutinho Correia)",
    "Belletti (Juliano Haus Belletti)",
    "Bartra (Marc Bartra Aregall)",
    "Castillo (José Carlos Castillo García-Tudela)",
    "Griezmann (Antoine Griezmann)",
    "Brugué (Joaquín Brugué Heras)",
    "Celades (Albert Celades López)",
    "Thiago Alcántara (Thiago Alcántara do Nascimento)",
    "Christensen (Andreas Bødtker Christensen)",
    "Estella (Juan José Estella Salas)",
    "Mora (Pere Valentí Mora Mariné)",
    "Valle (José Valle Mas)",
    "Òscar (Òscar García Junyent)",
    "Arocha (Ángel Arocha Guillén)",
    "Edmílson (José Edmílson Gomes de Moraes)",
    "Vidal (Arturo Erasmo Vidal Pardo)",
    "Gerard Martín (Gerard Martín Langreo)",
    "Zenden (Boudewijn Zenden)",
    "Rojo (Juan Carlos Pérez Rojo)",
    "Popescu (Gheorghe Popescu)",
    "Pesudo (José Manuel Pesudo Soler)",
    "Arnau (Patricio Arnau Pericás)",
    "Clos (Francisco Javier Clos Orozco)",
    "Dani Olmo (Daniel Olmo Carvajal)",
    "Mathieu (Jérémy Mathieu)",
    "Pinto (José Manuel Pinto Colorado)",
    "Rafinha (Rafael Alcántara do Nascimento)",
    "Pujol (Lluís Pujol Codina)",
    "Maxwell (Maxwell Scherrer Cabelino Andrade)",
    "Walter (Emil Walter Buckhard)",
    "Sagi-Barba (Emilio Sagi Liñán)",
    "Balmanya (Domingo Balmanya Perera)",
    "Nando (Fernando Muñoz García)",
    "Tello (Cristian Tello Herrera)",
    "Periko Alonso (Miguel Ángel Alonso Oyarbide)",
    "Benito (Benito García Cano)",
    "Pichi Alonso (Àngel Alonso Herrera)",
    "Dani (Daniel García Lara)",
    "Zambrotta (Gianluca Zambrotta)",
    "López Rekarte (Luis María López Rekarte)",
    "Goiburu (Severiano Goiburu Lopetegui)",
    "Guzmán (Ramón Guzmán Martorell)",
    "Parera (Manuel Parera Penella)",
    "Sans (Juan Sans Alsina)",
    "Ramón (Juan Ramón i Pera)",
    "Moreno (Tomás Hernández Burillo)",
    "Landaburu (Jesús Landaburu Sagüillo)",
    "Martí (Cristóbal Martí Batalla)",
    "Muller (Lucien Muller Schmidt)",
    "Milla (Luis Milla Aspas)",
    "Archibald (Steven Archibald)",
    "André Gomes (André Filipe Tavares Gomes)",
    "Pedraza (Ángel Pedraza Lamilla)",
    "Milito (Gabriel Alejandro Milito)",
    "Paco Martínez (Francisco Martínez Díaz)",
    "Claudio Bravo (Claudio Andrés Bravo Muñoz)",
    "Casadó (Marc Casadó Torras)",
    "Nicolau (Mateo Nicolau Garí)",
    "Bonano (Roberto Óscar Bonano)",
    "Alfonseda (Ramón Alfonseda Pous)",
    "Juan Carlos (Juan Carlos Rodríguez Moreno)",
    "Vantolrà (Martín Vantolrà Fort)",
    "Pizzi (Juan Antonio Pizzi Torroja)",
    "Arthur (Arthur Henrique Ramos de Oliveira Melo)",
    "Dest (Sergiño Gianni Dest)",
    "Iván Iglesias (Iván Iglesias Corteguera)",
    "Denis Suárez (Denis Suárez Fernández)",
    "Iñigo Martínez (Iñigo Martínez Berridi)",
    "Simão (Simão Pedro Fonseca Sabrosa)",
    "Sotil (Hugo Alejandro Sotil Yerén)",
    "Franco (Antonio Franco Florensa)",
    "Miró (Lluís Miró Doñate)",
    "Martín (José María Martín Rodríguez)",
    "Sonny Anderson (Anderson da Silva Nilmar)",
    "Rochemback (Fábio Rochemback)",
    "João Cancelo (João Pedro Cavaco Cancelo)",
    "Aloísio (Aloísio Pires Alves)",
    "Montoya (Martín Montoya Torralbo)",
    "Mingueza (Óscar Mingueza Garcia)",
    "Romário (Romário de Souza Faria)",
    "Song (Alexandre Dimitri Song Billong)",
    "Fortes (Francisco Fortes Calvo)",
    "Albaladejo (José Joaquín Albaladejo Gisbert)",
    "Navarro (Alfonso Navarro Perona)",
    "Sastre (José Sastre Perciba)",
    "Bogarde (Winston Lloyd Bogarde)",
    "Krankl (Johann Krankl)",
    "Marcos Aurelio (Marcos Aurellio Di Paulo)",
    "Couto (Fernando Manuel Silva Couto)",
    "Montesinos (Ramón Montesinos Calaf)",
    "Alcoriza (Francisco Alcoriza Gimeno)",
    "Witschge (Richard Peter Witschge)",
    "Larsson (Henrik Edward Larsson)",
    "Mas (Enrique Mas Mirandas)",
    "Czibor (Zoltán Czibor Suhai)",
    "Thuram (Ruddy Lilian Thuram-Ulien)",
    "Braithwaite (Martin Christensen Braithwaite)",
    "Pérez (Josep Maria Pérez Boixaderas)",
    "Morán (Enrique Morán Blanco)",
    "Maradona (Diego Armando Maradona Franco)",
    "Vicente (Vicente González Sosa)",
    "Ribelles (Enric Ribelles Seró)",
    "Riqui Puig (Ricard Puig Martí)",
    "Hanke (Jiří Hanke Hiron)",
    "Munir (Munir El Haddadi Mohamed)",
    "Carulla (Domingo Carulla Bertrán)",
    "Gracia (Antonio Gracia López)",
    "Ronald de Boer (Ronaldus de Boer)",
    "Arda Turan (Arda Turan)",
    "Amarilla (Raúl Vicente Amarilla Vera)",
    "Jordi Cruyff (Johan Jordi Cruijff Coster)",
    "Vítor Baía (Vítor Manuel Martins Baía)",
    "Vermaelen (Thomas Vermaelen)",
    "Juanito (Juan Díaz Sánchez)",
    "Tomé (Manuel Tomé Portela)",
    "Plattkó (Ferenc Plattkó Kopiletz)",
    "Bestit (Carlos Bestit Martínez)",
    "Hagi (Gheorghe Hagi)",
    "Aleix Vidal (Aleix Vidal Parreu)",
    "Gündoğan (İlkay Gündoğan)",
    "Alcácer (Francisco Alcácer García)",
    "Reina (José Manuel Reina Páez)",
    "Mendieta (Gaizka Mendieta Zabala)",
    "Paulinho (José Paulo Bezerra Maciel Júnior)",
    "Joan Garcia (Joan Garcia Pons)",
    "Rashford (Marcus Rashford)",
    "Mendonça (Jorge Alberto de Mendonça Paulino)",
    "Ronaldo (Ronaldo Luís Nazário de Lima)",
    "Calo (Ricardo Rodríguez Álvarez)",
    "Seminario (Juan Roberto Seminario Rodríguez)",
    "Christanval (Philippe Charles Lucien Christanval)",
    "Ibrahimović (Zlatan Ibrahimović)",
    "Digne (Lucas Digne)",
    "Iñaki Peña (Ignacio Peña Sotorres)",
    "Marcos Alonso (Marcos Alonso Mendoza)",
    "Dueñas (Teófilo Dueñas Samper)",
    "Aleñá (Carles Aleñá Castillo)",
    "João Félix (João Félix Sequeira)",
    "Geovanni (Geovanni Deiberson Maurício Gómez)",
    "Kessié (Franck Yannick Kessié)",
    "Kodro (Mehmed Kodro Šejtanić)",
    "Vidal I (Luis María Vidal Planella)",
    "Riquelme (Juan Román Riquelme)",
    "Trincão (Francisco António Machado Mota Castro Trincão)",
    "Memphis (Memphis Depay)",
    "Szczęsny (Wojciech Tomasz Szczęsny)",
    "Amarillo (Alfredo Amarillo Kechichian)",
    "Cristóbal (Cristóbal Parralo Aguilera)",
    "Ezquerro (Santiago Ezquerro Marín)",
    "Junior Firpo (Héctor Junior Firpo Adames)",
    "Ćirić (Dragan Ćirić)",
    "Bernal (Marc Bernal Casas)",
    "Salva (Salvador García Puig)",
    "Anguera (Antonio Anguera Bernaus)",
    "Romeu (Oriol Romeu Vidal)",
    "Luis García (Luis Javier García Sanz)",
    "Alcántara (Paulino Alcántara Riestra)",
    "Alfonso (Alfonso Pérez Muñoz)",
    "Petit (Emmanuel Laurent Petit)",
    "Van Bommel (Mark Peter Gertruda Andreas van Bommel)",
    "Giovani dos Santos (Giovani Álex dos Santos Ramírez)",
    "Ramírez (Andrés Ramírez Gandullo)",
    "Canito (José Cano López)",
    "Blanc (Laurent Robert Blanc)",
    "Nico (Nicolás González Iglesias)",
    "Hughes (Leslie Mark Hughes)",
    "Hleb (Aliaksandr Paŭlavič Hleb)",
    "Vila (Jordi Vila Soler)",
    "Szegedi (Nicolae Simatoc)",
    "Torralba (Ramón Torralba Larraz)",
    "Sancho (Agustín Sancho Agustina)",
    "León (Aurelio León Rovira)",
    "Fernando Navarro (Fernando Navarro Corbacho)",
    "Afellay (Ibrahim Afellay)",
    "Macizo (José Cirilo Macizo Cañadas)",
    "Jeffrén (Jeffrén Isaac Suárez Bermúdez)",
    "Barrios (José Antonio Barrios Olivero)",
    "Aldecoa (Emilio Aldecoa Gómez)",
    "Rafa (Juan Rafa Mas)",
    "Zabala (Luis Zabala Echevarría)",
    "Coco (Francesco Coco)",
    "Pellicer (Carlos Pellicer Vázquez)",
    "Berkessy (Elemér Berkessy Cöji)",
    "Coll (Luis Coll Hortal)",
    "Arnau (Francesc Arnau Grabalosa)",
    "Litmanen (Jari Olavi Litmanen)",
    "Sandro (Sandro Ramírez Castillo)",
    "Cillessen (Jacobus Antonius Peter Johannes Cillessen)",
    "Camps (Antonio Camps Bau)",
    "Morera (Alejandro Morera Soto)",
    "Fradera (Esteve Fradera Serrat)",
    "Andersson (Patrik Jonas Andersson)",
    "Carreño (Jorge Carreño Padilla)",
    "Canal (José Canal Viñas)",
    "García (Antonio García García)",
    "Cuenca (Juan Isaac Cuenca López)",
    "Pjanić (Miralem Pjanić)",
    "Fort (Héctor Fort García)",
    "Sampedro (Francisco Sampedro Lluesma)",
    "Marinho (Mario Peres Ulibarri)",
    "De Jong (Luuk de Jong)",
    "Pau Víctor (Pau Víctor Delgado)",
    "Valverde (Ernesto Valverde Tejedor)",
    "Areso (Pedro Pablo Areso Aramburu)",
    "Carreras (Lluís Carreras Ferrer)",
    "Jonathan dos Santos (Jonathan dos Santos Ramírez)",
    "Bardghji (Roony Bardghji)",
    "Cuéllar (Ángel Manuel Cuéllar Llanos)",
    "Quaresma (Ricardo Andrade Quaresma Bernardo)",
    "Serrat (Adjutori Serrat Giró)",
    "Castro (Santiago Castro Anido)",
    "Amorós (Francisco Amorós López)",
    "Saura (Vicente Saura Villalonga)",
    "Pablo Torre (Pablo Torre Carral)",
    "Franch (Josep Franch Xargay)",
    "Areta II (Esteban Areta Vélez)",
    "Llorens (Ramón Llorens Pujadas)",
    "Uriach (Jaime Uriach Lafita)",
    "Mandi (Armando Fernández Prieto)",
    "Amador (Amador Lorenzo Lemos)",
    "Amunike (Emmanuel Amuneke)",
    "Prosinečki (Robert Prosinečki)",
    "Planas (José Planas Artés)",
    "Bosch (Andrés Bosch Girona)",
    "Font (Valentín Font Oller)",
    "Enrique Fernández (Enrique Fernández Viola)",
    "Gamonal (Luis Gamonal Gago)",
    "Corominas (Miquel Corominas Queralt)",
    "Goyvaerts (Fernand August Goyvaerts Deyrdey)",
    "Cubilla (Luis Alberto Cubilla Almeida)",
    "Sierra (Vicente Sierra Sanz)",
    "Pellegrino (Mauricio Andrés Pellegrino Luna)",
    "Quique Estebaranz (Juan Enrique Estebaranz López)",
    "Jorquera (Albert Jorquera Fortià)",
    "Malcom (Malcom Filipe Silva de Oliveira)",
    "Cos (Bernardo Patricio Cos Luján)",
    "Aubameyang (Pierre-Emerick Emiliano François Aubameyang)",
    "Santos (Victoriano Santos Troya)",
    "Quique (Enrique Martín Navarro)",
    "Sagrera (Salvador Sagrera Pedret)",
    "Déhu (Frédéric Fabian William Déhu)",
    "Cáceres (José Martín Cáceres Silva)",
    "Deulofeu (Gerard Deulofeu Lázaro)",
    "Julián Rubio (Julián Rubio Sánchez)",
    "Corró (Manuel Antonio Esteva Corró)",
    "Dutruel (Richard Philippe Dutruel)",
    "Oliveros (Ángel Oliveros Jiménez)",
    "Peris (Enrique Peris de Vargas)",
    "Salas (Pascual Serapio Salas Usón)",
    "Pinto (José Pinto Rosas)",
    "Okunowo (Samuel Gbenga Okunowo)",
    "Adama (Adama Traoré Diarra)",
    "Neto (Norberto Murara Neto)",
    "Sergi (Sergi López Segú)",
    "Torrent (Juan Torrent Solé)",
    "Juanjo (Juan José Enríquez Gómez)",
    "Cabanes (Mario Cabanes Sabat)",
    "Arana (José Arana Goróstegui)",
    "Emilín (Emilio García Martínez)",
    "Ribas (Francesc Ribas Sanglas)",
    "Davids (Edgar Steven Davids)",
    "Eskurza (Xabier Eskurza García)",
    "Maxi López (Maximiliano Gastón López)",
    "Diego (Fernando Diego Moliner)",
    "Munlloch (Julio Munlloch Martí)",
    "Garcerán (Francisco Garcerán Hernández)",
    "Riba (José Riba Nuet)",
    "Aretio (Juan Rodríguez Aretio)",
    "Soler (Jesús Salvador Soler Blanchart)",
    "Ilaix Moriba (Moriba Kourouma Kourouma)",
    "Mir (Miquel Mir Genes)",
    "Amechazurra (Manuel Amechazurra Guazo)",
    "Iborra (José Iborra Blanco)",
    "Vergara (Julián Vergara Medrano)",
    "Estrems (Pedro Estrems Navarra)",
    "Aloy (Luis Aloy Vidal)",
    "Martínez (Vicente Martínez Duart)",
    "Lecuona (Ramón Lecuona Bordegaray)",
    "Herrerita (Eduardo Herrera Bueno)",
    "Homedes (Ramón Homedes Vallés)",
    "Fontàs (Andreu Fontàs Prat)",
    "Vitor Roque (Vitor Hugo Roque Ferreira)",
    "Forns (Romà Forns i Saldaña)",
    "García Castany (José Pablo García Castany)",
    "Surroca (Salvador Martínez Surroca)",
    "Pagès (Josep Pagès Pascual)",
    "Argemí (José Argemí Rocabert)",
    "Badenes (Manuel Badenes Calduch)",
    "Moll (Dagoberto Moll Sequeira)",
    "José Mari (José María García Lafuente)",
    "Nayim (Mohamed Ali Amar)",
    "Toni Velamazán (Antonio Velamazán Tejedor)",
    "Marañón (Ramón de Pablo Marañón)",
    "Vinyals (Francesc Vinyals Bou)",
    "Saló (José Saló Baliarda)",
    "Valero (José Valero Martín)",
    "Florencio (Florencio Caffaratti Chisalvo)",
    "Sorín (Juan Pablo Sorín)",
    "Suco (Andrés Joaquín Parada Alvite)",
    "Víctor Sánchez (Víctor Sánchez Mata)",
    "Moreno (Juan Carlos Moreno Rodríguez)",
    "Chygrynskiy (Dmytro Anatoliyovych Chygrynskiy)",
    "Juanito (Juan García Torres)",
    "Pinilla (Antonio Pinilla Miranda)",
    "Alfred Massana (Alfred Massana Urgellès)",
    "Romero (José Luis Romero Robledo)",
    "Abde (Abdessamad Ezzalzouli)",
    "Betancourt (Francisco Betancourt Cocinero)",
    "Colino (Vicente Colino Hierro)",
    "Virgós (Francisco Virgós Baello)",
    "López López (Francisco López López)",
    "Helguera (Daniel Helguera Pérez)",
    "Korneev (Igor Vladimirovich Korneev)",
    "Dugarry (Christophe Jérôme Dugarry)",
    "Samper (Sergi Samper Montaña)",
    "Carles Pérez (Carles Pérez Sayol)",
    "Òscar López (Òscar López Hernández)",
    "Roura (Jordi Roura Solà)",
    "Pais (Antonio Pais Castroagudín)",
    "Ramoní (Ramón Díaz Cruz)",
    "Obiols (José Obiols Navarro)",
    "Llácer (Ignacio Llácer Sornosa)",
    "Palau (Josep Palau Busquet)",
    "Reñé (Lluís Reñé Padrisa)",
    "Romea (Francisco Romea Hernando)",
    "Torra (Miguel Torra Monzó)",
    "Riera (Abelardo Riera Fernández)",
    "Ceballos (Cristobal Ceballos García)",
    "Angoy (Jesús Mariano Angoy Gil)",
    "Roberto Dinamite (Carlos Roberto de Oliveira)",
    "Fernández (Pedro Fernández Cantero)",
    "Paredes (Bartolomé Paredes Feliu)",
    "Font (Juan Font Mañé)",
    "Trujillo (Juan Trujillo Domínguez)",
    "Argila (Fernando de Argila Pazzaglia)",
    "Va (Manuel Va Esteve)",
    "Lopetegui (Julen Lopetegi Agote)",
    "Sánchez Jara (Francisco Javier Sánchez Jara)",
    "Damià (Damià Abella Pérez)",
    "Espart (Xavier Espart Font)",
    "Bustillo (Miguel Ángel Bustillo Lafoz)",
    "Bio (Williams Silvio Modesto Verísimo)",
    "Reguera (Eduard Reguera Andreu)",
    "Muntaner (Juan Muntaner Roig)",
    "Noguera (Antonio Noguera Parés)",
    "Pablo Alfaro (Pablo Alfaro Armengot)",
    "Sergio García (Sergio García de la Fuente)",
    "Gumbau (Gerard Gumbau Garriga)",
    "Demir (Yusuf Demir)",
    "Unzué (Juan Carlos Unzué Labiano)",
    "Bru (Francisco Bru Sanz)",
    "Berdié (Josep Berdié Places)",
    "Irizar (José Marcelino Yrízar Urbizu)",
    "Bru (Lluís Bru Masipó)",
    "Silveira (Alcides Vicente Silveira Montero)",
    "Borràs (Joaquín Borràs Canut)",
    "Escudero (Jaime Escudero Etxebarria)",
    "Jutglà (Ferran Jutglà Blanch)",
    "Gràcia (Josep Climent Gràcia Bosch)",
    "Vidal (Manuel Vidal Hermosa)",
    "Laredo (José María Laredo Laredo)",
    "Villacampa (Juan Villacampa Presegué)",
    "Bardina (José Bardina Bellera)",
    "Nieto (José García-Nieto Romero)",
    "Montserrat (Antonio Montserrat Carrasquer)",
    "Rodri (Sergio Rodríguez García)",
    "Douglas (Douglas Pereira dos Santos)",
    "Carlos Comamala (Carlos Comamala López-Del Pan)",
    "Charles Wallace (Charles Malcolm Wallace Midgley)",
    "Celdrán (Juan Antonio Celdrán Montoya)",
    "Coma (Francesc Coma Vives)",
    "Zamora (Ricardo Zamora Martínez)",
    "Pascual (Joaquín Pascual Jiménez)",
    "Montané (Joaquim Montané Martí)",
    "Roig (Joaquín Juan Roig)",
    "Padrón (José Padrón Martín)",
    "Torredeflot (Domingo Torredeflot Solé)",
    "Basilio (Basilio Nieto Barranco)",
    "Periche (Pedro Rocamora Pacheco)",
    "Fuentes (Manuel Sebastián Fuentes Campesino)",
    "Pascual (Pedro Pascual Ros)",
    "Santamaría (Sergio Santamaría González)",
    "Bellerín (Héctor Bellerín Moruno)",
    "Guiu (Marc Guiu Paz)",
    "Rüştü (Rüştü Reçber)",
    "Amigó (Vicente Amigó Navarro)",
    "Rodríguez (José Rodríguez Vázquez)",
    "Endériz (Eduardo Bibiano Endériz Artajona)",
    "Cortés (Alfonso Cortés de Tena Dávila)",
    "Rocasolano II (Juan Rocasolano Camacho)",
    "Martínez (Vicente Martínez Alama)",
    "Navarro (Joaquín Navarro Perona)",
    "Rueda (César Rueda Gonzalo)",
    "Giménez (Humberto Ramón Giménez Martínez)",
    "Vilà (Joan Vilà Bosch)",
    "Romerito (Julio César Romero Insfrán)",
    "Luis Cembranos (Luis Cembranos Martínez)",
    "Nano (Fernando Macedo da Silva Rodilla)",
    "Albertini (Demetrio Albertini)",
    "Wagué (Moussa Wagué)",
    "Domínguez (Sergi Domínguez Viloria)",
    "Manolo (Manuel Muñoz Navas)",
    "Grau (Joan Francesc Grau)",
    "Percy Wallace (Percival Francis Wallace Midgley)",
    "Bau (Gabriel Bau Fortanete)",
    "Mallorquí (Casimiro Mallorquí Tutusaus)",
    "Beitia (Gonzalo Díaz Beitia)",
    "Medrano (Carlos Domingo Medrano Lazcano)",
    "García (Manuel García Ribes)",
    "Gual (Miguel Gual Agustina)",
    "Santacatalina (Nicolás Santacatalina Ferreres)",
    "Cerveró (Manuel Cerveró Chiva)",
    "Serratusell (José Serratusell Abella)",
    "Maristany (Francisco Javier Álvarez Maristany)",
    "Szalay (Tibor Szalay Csikos)",
    "Yerry Mina (Yerry Fernando Mina González)",
    "Quique (Francisco Pérez Cubas)",
    "Hilario (Juan Hilario Marrero Pérez)",
    "Vučević (Goran Vučević)",
    "Mario Rosas (Mario Alberto Rosas Montero)",
    "Todibo (Jean-Clair Dimitri Roger Todibo)",
    "Agüero (Sergio Leonel Agüero del Castillo)",
    "Alarcón (Ángel Alarcón Galiot)",
    "Dro (Pedro Fernández Sarmiento)",
    "Onésimo (Onésimo Sánchez González)",
    "Herrera (Sebastián Herrera Zamora)",
    "Solà (Romà Solà Brunet)",
    "Arsenio Comamala (Arsenio Comamala López-Del Pan)",
    "Apolinario (Alejandro Rodríguez Apolinario)",
    "Hermes González (Hermes Celestino González Flores)",
    "Serafín (Serafín García Muñoz)",
    "Blanco (Eusebio Blanco Añaños)",
    "Lakatos (José Landazábal Uriarte)",
    "Barceló (José Barceló Font)",
    "Galvany (Salvador Galvany Ventura)",
    "Nolito (Manuel Agudo Durán)",
    "Arnaiz (José Manuel Arnaiz Díaz)",
    "Vidal (Manuel Vidal de Cárcer)",
    "Tejedor (Joaquín Tejedor Tresserras)",
    "Goicolea (Francisco Javier Goicolea Areitio)",
    "Rodri (Andrés Rodríguez Serrano)",
    "Escaich (Xavier Escaich Ferrer)",
    "Enke (Robert Enke)",
    "Crosas (Marc Crosas Luque)",
    "Muniesa (Marc Muniesa Martínez)",
    "Masip (Jordi Masip López)",
    "Murillo (Jeison Fabián Murillo Cerón)",
    "Miranda (Juan Miranda González)",
    "Álvaro Sanz (Álvaro Sanz Catalán)",
    "Torrents (Jofre Torrents Salvat)",
    "Rositzky (Walter Cäsar Max Rositzky)",
    "Steel (Alexander Steel)",
    "Bori (Mariano Pedro de Roma Bori Viaud)",
    "Jack Greenwell (John Richard Greenwell)",
    "Baonza (Francisco Baonza García)",
    "Artigas (Salvador Artigas Sahún)",
    "Espuny (Alejandro Espuny Casas)",
    "Rusky (Antonio García Ramos)",
    "Botella (José Botella Almodóvar)",
    "Maqueda (Pablo José Maqueda Andrés)",
    "Boateng (Kevin-Prince Boateng)",
    "Campabadal (Ramón Campabadal Martí)",
    "Gámiz (David Gámiz Viana)",
    "Pachi (Santiago Pérez Luzuriaga)",
    "Colominas (Juan Colominas Llavorés)",
    "Duró (José Duró Beal)",
    "Félix (Félix Palomares Poveda)",
    "Gordon (Anthony Michael Gordon)",
    "Adeyemi (Karim-David Adeyemi)",
    "Trashorras (Roberto Trashorras Gayoso)",
    "Rubén (Rubén Iván Martínez Andrade)",
    "Víctor Vázquez (Víctor Vázquez Solsona)",
    "Dongou (Jean Marie Dongou Tsafack)",
    "Kaptoum (Wilfrid Jaures Kaptoum Fangang)",
    "Marlon (Marlon Santos da Silva Barbosa)",
    "Chumi (Juan Brandariz Movilla)",
    "De la Fuente (Konrad de la Fuente)",
    "Akhomach (Ilias Akhomach Chakkour)",
    "Àlex (Alejandro García Casañas)",
    "Quirante (José Quirante Pineda)",
    "Pakán (Francesc Armet de Castellví)",
    "Morales (Antonio Morales Veloso)",
    "Allack (Frank Albert Allack)",
    "Oller (Miquel Oller)",
    "Sanjuán (José Sanjuán Ibáñez)",
    "Ekelund (Ronnie Michael Ekelund)",
    "Castejón (Manuel Castejón)",
    "Costa (Josep Costa Faura)",
    "Santiago Massana (Santiago Massana Urgellès)",
    "Garchitorena (Juan Garchitorena de Carvajal)",
    "Sesumaga (Félix Sesumaga Ugarte)",
    "Galicia (Ricardo Galicia Nobiols)",
    "Plaza (Fernando Acacio Plaza Sánchez)",
    "Cella (Artur Cella Quivent)",
    "Elías (Baldiri Elías Parés)",
    "Sabaté Solà (Leandro Sabaté Solà)",
    "Aylagas (Máximo Aylagas Herrera)",
    "Isal (Gabriel Isal Miró)",
    "Peiró (Jaime Peiró Arbonés)",
    "Llangostera (Francesc Damià Llangostera Pujol)",
    "Villarroya (Josep Villarroya Pérez)",
    "Colomé (José Colomé Rovira)",
    "González (Manuel González González-Couce)",
    "Francàs (José Francàs Casas)",
    "Polo (Antonio Márquez Jiménez)",
    "Orriols (Arturo Orriols Faura)",
    "García (Fernando García Lorenzo)",
    "Morera (Vicente Morera Amigó)",
    "Da Silva (Lucidio Batista da Silva)",
    "Nieto (Francisco Nieto Sánchez)",
    "Tarrés (Isidre Tarrés Caubet)",
    "Arpón (Óscar Arpón Ochoa)",
    "Emerson Royal (Emerson Aparecido Leite de Souza)",
    "Rodri (Rodrigo Hernández Cascante)",
    "Dani Tortolero (Daniel Tortolero Núñez)",
    "Verdú (Joan Verdú Fernández)",
    "Abraham (Abraham González Casanova)",
    "Xavi Torres (Xavier Torres Buigues)",
    "Oier Olazábal (Oier Olazábal Paredes)",
    "Planas (Carles Planas Antolínez)",
    "Cámara (Juan del Carmen Cámara Mesa)",
    "Cardona (Marc Cardona Rovira)",
    "Toni Fernández (Antonio Fernández Casino)",
    "Marqués (Tomás Noël Marqués Morera)",
    "Quique Álvarez (Enrique Álvarez Sanjuán)",
    "Mario (Pedro Mario Álvarez Abrante)",
    "Ros (Ramón Ros Badia)",
    "Christiansen (Thomas Christiansen Tarín)",
    "Huguet (Jaume Huguet Garcia)",
    "Graell (José Graell Pons)",
    "Pattullo (George Simpson Frynan Pattullo)",
    "Berrondo (José Berrondo Silva)",
    "Molins (Pere Molins Pascual)",
    "Rifé (Llorenç Rifé Climent)",
    "Mas (Pere Mas Pujol)",
    "Prais (Luis Prais Bernardo)",
    "Estévez (Francisco Estévez)",
    "Aramburu (Francisco Aramburu)",
    "Just (Francesc Just)",
    "Musterós (Rafael Musterós Bori)",
    "Parera II (Ramón Parera Penella)",
    "Bayo (José Bayo Bernad)",
    "Vendrell (José Vendrell Lladó)",
    "Loayza (Miguel Ángel Loayza Ríos)",
    "Olmo (Jesús Olmo Lozano)",
    "Marc Valiente (Marc Valiente Hernández)",
    "Cantalapiedra (Aitor Cantalapiedra Fernández)",
    "Oriol Busquets (Oriol Busquets Mas)",
    "Collado (Álex Collado Gutiérrez)",
    "Carreras (Juan Carlos Carreras Domingo)",
    "Bussot (Francesc Bussot Garreta)",
    "Oro (Manuel Oro Comas)",
    "Cifuentes (Esteban Cifuentes Surroca)",
    "Costa (Agustín Costa Aymerich)",
    "Cruz (Manuel de la Cruz Martínez)",
    "Aubach (José Aubach Gort)",
    "García (Manuel García Capdevila)",
    "Valcárcel (Miguel Ángel Valcárcel Lorenzo)",
    "Gonzalvo I (Julio Gonzalvo Falcón)",
    "Cardús (Josep Cardús Aguilar)",
    "Tito (Carmelo Albaladejo López)",
    "Vila (José Vila Escuer)",
    "Caldentey (Pedro Caldentey Bauzá)",
    "Gabrich (Jorge Luis Luján Gabrich Cinalli)",
    "Linde (David Linde Sales)",
    "Jofre (Jofre Mateu González)",
    "Ludovic (Ludovic Sylvestre)",
    "Cuadrado (Ibán Javier Cuadrado Alonso)",
    "David Sánchez (David Sánchez Rodríguez)",
    "Javito (Francisco Javier Peral Perianes)",
    "Oriol Riera (Oriol Riera Magem)",
    "Botía (Alberto Tomás Botía Rabasco)",
    "Gai Assulin (Gai Yigaal Assulin Hazan)",
    "Miño (Rubén Miño Peralta)",
    "Riverola (Martí Riverola Bataller)",
    "Sergi Gómez (Sergi Gómez Solà)",
    "Patric (Patricio Gabarrón Gil)",
    "Nili (Francisco José Perdomo Borges)",
    "Monchu (Ramón Rodríguez Jiménez)",
    "Matheus Fernandes (Matheus Fernandes Siqueira)",
    "Aleix Garrido (Aleix Garrido Cañizares)",
    "Cuenca (Andrés Cuenca Cejudo)",
    "Cortés (Álvaro Cortés Moyano)",
    "Dani Rodríguez (Daniel Rodríguez Crespo)",
    "Casas (Jordi Casas Rodríguez)",
    "Aguirreche (Leandro Aguirreche Picabea)",
    "Llonch (Joan Llonch)",
    "Sanz (Francisco Sanz de Gabilondo)",
    "Steinberg (Udo Steinberg Werle)",
    "Espelta (Domingo Espelta Mussons)",
    "Peris (Lisandro Peris de Vargas)",
    "Billy Lambe (William Charles Lambe)",
    "Carlier (Jaques Carlier)",
    "Larraz (Francesc Larraz Lordán)",
    "Jiménez (Manuel Jiménez Rodríguez)",
    "Matamala (Antonio Matamala Sistac)",
    "Morris (Miguel Samuel Morris Yrisarri)",
    "Normand (Enrique Normand Faurie)",
    "Homs (Marià Homs Montserrat)",
    "Martínez-Sagi (Armando Ricardo Eugenio Martínez Sagi)",
    "Blanco (Luis Blanco Peyrona)",
    "Hospital (Jaime Hospital Gallego)",
    "Calvet (Josep Calvet Vilana)",
    "Mas (Juan Mas Llobera)",
    "Covelo (José Antonio García Alonso)",
    "Bermudo (David Bermudo Rubio)",
    "Cristian (Cristian Hidalgo González)",
    "Jordi Gómez (Jordi Gómez García-Penche)",
    "Soriano (Jonathan Soriano Casas)",
    "Ié (Edgar Miguel Ié)",
    "Halilović (Alen Halilović)",
    "Borja López (Borja López Menéndez)",
    "Carbonell (Àlex Carbonell Vallés)",
    "David Costas (David Costas Cordal)",
    "Cucurella (Marc Cucurella Saseta)",
    "Cuenca (Jorge Cuenca Barreno)",
    "Abel Ruiz (Abel Ruiz Ortega)",
    "Mika Mármol (Mika Mármol Medina)",
    "Estanis (Estanislau Pedrola Fortuny)",
    "Carlos (Carlos Antonio Muñoz Cobo)",
    "Capella (Jordi Capella Rovira)",
    "Solà (Cristóbal Solà Coll)",
    "Portas (Conrad Portas Burcet)",
    "Cambra (Luis Cambra Hernani)",
    "Sanfeliu (Ramón Sanfeliu Martínez)",
    "Escrig (Samuel Narciso Escrig Lliberós)",
    "Jordà (Joaquim Jordà Pons)",
    "Vela (Constantino Vela de la Fuente)",
    "Miranda (Ramón Miranda Pérez)",
    "Quico (Francisco José Tejera Castellanos)",
    "Ruano (Domingo Ruano Carreño)",
    "Saurina (Joan Saurina Rovira)",
    "Miranda (Luis Miranda Junco)",
    "Olivé (Javier Olivé Millet)",
    "Herrera (Juan Herrera Hernández)",
    "Font (Vicente Font Mestres)",
    "Casamor (Rafael Casamor Vila)",
    "Soto (Luis Soto Valverde)",
    "Peralta (Francisco Peralta Acero)",
    "Ferrer (Miguel Ferrer Aymami)",
    "Castañer (Luis Castañer Viñas)",
    "Abellán (Francisco Abellán Cámara)",
    "Aranda (José Miguel Aranda Moreno)",
    "Bueno (Alejandro Bueno Román)",
    "Cristóbal Sánchez (Cristóbal Sánchez López)",
    "Durán (Jordi Durán Ganduxer)",
    "Lobo (Manuel Lobo Lobo)",
    "Martín Domínguez (José Antonio Martín Domínguez)",
    "Padilla (Antonio Padilla Vertedor)",
    "Retuerto (Miguel Retuerto Egea)",
    "Serer (José Pérez Serer)",
    "Geli (Delfí Geli Roura)",
    "Lucendo (Jesús Julián Lucendo Heredia)",
    "García Pimienta (Francisco Javier García Pimienta)",
    "Juanjo (Juan José Carricondo Pérez)",
    "Rufete (Francisco Joaquín Pérez Rufete)",
    "Setvalls (Josep Setvalls Morera)",
    "Xavi Roca (Francesc Xavier Roca Mateo)",
    "Martos (Francisco Javier Martos Espigares)",
    "Masó (Ramón Masó Vallmajó)",
    "Montañés (Francisco Montañés Claverias)",
    "Orlandi (Andrea Orlandi Stabilin)",
    "Pitu Comadevall (Josep Maria Comadevall Crous)",
    "Fali (Rafael Romero Serrano)",
    "Rueda (José Manuel Rueda Sampedro)",
    "Riad (Chadi Riad Dnanou)",
    "Gabriel Jesus (Gabriel Fernando de Jesus)",
    "Hamza Abdelkarim (Hamza Mohamed Abdelkarim Elsayed Selim)",
    "Gonzalo (Gonzalo Sánchez Moreno)",
    "Peña (Carlos González Peña)",
    "Mora (José Francisco Mora Altava)",
    "Kiko Femenía (Francisco Femenía Far)",
    "Morer (Daniel Morer Cabrera)",
    "Jandro (Alejandro Orellana Gómez)",
    "Reis (Ludovit Reis)",
    "Akieme (Sergio Akieme Rodríguez)",
    "Tenas (Arnau Tenas Ureña)",
    "Valle (Álex Valle Gómez)",
    "Astralaga (Ander Astralaga Aranguren)",
    "Kochen (Diego Kochen)",
    "Unai Hernández (Unai Hernández Lorenzo)",
    "Yaakobishvili (Áron Yaakobishvili)",
    "Guillermo (Guillermo Fernández Casino)",
    "Farré (Landry Cephas Farré Miró)",
    "Darvich (Yanis Noah Darvich)",
    "Aller (Eder Aller González)",
    "Hernández (Juan Hernández Torres)",
    "Vinyals (Jordi Vinyals Martori)",
    "David García (David García Haro)",
    "Almasqué (Albert Almasqué Domènech)",
    "Müller (Julius Karl Theodor Müller Wislicenus)",
    "Puig (Miquel Puig)",
    "Thalmann (Ernst Alfred Thalmann)",
    "Witte (Hermann August Cornell Witte)",
    "Scarone (Héctor Pedro Scarone Beretta)",
    "Blay (Andrés Blay Raja)",
    "Diagne (Diawandou Diagne Niang)",
    "Dani Romera (Daniel Romera Andújar)",
    "Ortolá (Adrián Ortolá Vañó)",
    "Guillem Jaime (Guillem Jaime Serrano)",
    "Comas (Arnau Comas Feixas)",
    "Segura (Joan Segura)",
    "Burguete (Joan Garcia Burguete)",
    "Dos Santos (Fausto dos Santos)",
    "Jaguaré (Jaguaré Bezerra de Vasconcelos)",
    "Cruz (Victorio Cruz Riverol)",
    "Barrachina (Vicent Barrachina Rubio)",
    "Aldana (Cecilio Aldana Yagüe)",
    "Mesa (Juan Mesa Castellano)",
    "Cánovas (Francisco Cánovas Candel)",
    "Avelino (Avelino Senón Martínez)",
    "Pedrín (Pedro Eloy López Arteaga)",
    "Arocena (José Antonio Arocena Aramburu)",
    "Basora II (Joaquín Basora Brunet)",
    "Boneu (Jaime Boneu Canela)",
    "Vicedo (Enrique Vicedo Pascual)",
    "Olmedo (Melanio Olmedo Bretón)",
    "Jofra (Francisco Jofra Boluda)",
    "Isidro (Isidro Acosta Hernández)",
    "Comas (Ismael Comas Solanot)",
    "Rodés (José Rodés Vernet)",
    "Lucho (José Luis Dávila Comesaña)",
    "Valiente (Juan Valiente Martos)",
    "Capó (Joan Capó Coll)",
    "Aicart (Pedro Aicart Iniesta)",
    "Corral (Aurelio Corral Aguilera)",
    "Pérez Contreras (Juan Pérez Contreras)",
    "Cleo (Cleo Inacio Hickman)",
    "Fernández (Luis Miguel Fernández Domínguez)",
    "Lluís (Lluís Garcia Gonzalo)",
    "Font (Josep Font Rosell)",
    "Endrino (Juan Gregorio Endrino Nieto)",
    "Manolo Hierro (Manuel Ruiz Hierro)",
    "Julio Iglesias (Julio José Iglesias Rouget)",
    "Quique Martín (Enrique Martín Sánchez)",
    "Guzmán (Francisco Javier Doz Guzmán)",
    "Porto (Fernando José Porto Collazo)",
    "Felip (Felip Ortiz Martínez)",
    "Rubén (Rubén Martínez Caballero)",
    "Ferrón (Jordi Ferrón Forné)",
    "Marcelo (Anderson Marcelo da Silva)",
    "Arnau (Arnau Caldentey Riera)",
    "Lolo (Manuel González García)",
    "Urko (Urko Rafael Pardo Goas)",
    "Espasandín (Víctor Manuel Espasandín Facal)",
    "Ezkieta (Jokin Ezkieta Mendiburu)",
    "Saverio (Javier Enrique Delgado Saverio)",
    "Manaj (Rey Aldo Manaj)",
    "Ramos Mingo (Santiago Martín Ramos Mingo)",
    "Carević (Lazar Carević)",
    "De Vega (Lucas de Vega Lima)",
    "Prim (Pau Prim Coma)",
    "Faye (Mikayil Ngor Faye)",
    "Olmedo (Alexis Olmedo Vila)",
    "Fariñas (Brian Fariñas Pérez)",
    "Livaković (Dominik Livaković)",
    "Pesquer (Jordi Pesquer Barraquer)",
]


def get_today_msk_str() -> str:
    """Возвращает дату по МСК в формате YYYY-MM-DD (сутки 00:00-00:00 МСК)."""
    return datetime.now(MOSCOW_TZ).strftime("%Y-%m-%d")


def get_player_for_user(user_id: int) -> str:
    today = get_today_msk_str()
    seed = f"{user_id}-{today}"
    rng = random.Random(seed)
    return rng.choice(PLAYERS)


async def inline_query(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    user_id = update.inline_query.from_user.id
    player = get_player_for_user(user_id)

    text = f"Сегодня я {player} 🔵🔴"

    result = InlineQueryResultArticle(
        id=str(uuid.uuid4()),
        title="Кто ты из Барселоны сегодня?",
        description="Нажми, чтобы узнать",
        input_message_content=InputTextMessageContent(text),
        thumbnail_url="https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.png",
    )

    await update.inline_query.answer([result], cache_time=1, is_personal=True)


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(
        "Привет! Я бот \"Кто ты из Барселоны сегодня?\".\n\n"
        "Чтобы воспользоваться мной, в ЛЮБОМ чате (в том числе в этом) "
        "начни вводить @ИмяЭтогоБота — снизу появится подсказка, "
        "нажми на неё, и я скажу, кем ты сегодня являешься из состава Барсы. "
        "Результат сохраняется за тобой на все сутки (до 00:00 по Москве)."
    )


def main() -> None:
    token = os.environ.get("BOT_TOKEN")
    if not token:
        raise RuntimeError(
            "Не найден токен бота. Установи переменную окружения BOT_TOKEN "
            "(токен выдаёт @BotFather)."
        )

    application = Application.builder().token(token).build()

    application.add_handler(CommandHandler("start", start))
    application.add_handler(InlineQueryHandler(inline_query))

    logger.info("Бот запущен, жду инлайн-запросы...")
    application.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()
